# Site settings
title: Candinho Jr
description: My personal page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Candinho Jr
user_description: Undergraduate student in Information Systems from the Federal University of Santa Catarina (UFSC). Passionate about software quality. Quality Assurance Intern at Bridge Lab. Web developer in his spare time.
user_title: QA && Web Developer
email: candinholuiz@gmail.com
twitter_username: lorem_ipsum
github_username:  candinhojr
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
